//! Architecture pattern detection and drift analysis

mod boundaries;
mod patterns;
mod drift;

pub use boundaries::*;
pub use patterns::*;
pub use drift::*;

use crate::graph::DependencyGraph;
use crate::types::*;
use anyhow::Result;

pub struct ArchitectureAnalyzer {
    pattern_detectors: Vec<Box<dyn PatternDetector>>,
    boundary_inferencers: Vec<Box<dyn BoundaryInferencer>>,
}

impl ArchitectureAnalyzer {
    pub fn new() -> Self {
        Self {
            pattern_detectors: vec![
                Box::new(patterns::LayeredArchitectureDetector),
                Box::new(patterns::ModularArchitectureDetector),
                Box::new(patterns::HexagonalArchitectureDetector),
            ],
            boundary_inferencers: vec![
                Box::new(boundaries::PathBasedInferencer),
                Box::new(boundaries::NamingBasedInferencer),
                Box::new(boundaries::AnnotationBasedInferencer),
            ],
        }
    }
    
    pub fn detect_patterns(&self, graph: &DependencyGraph) -> Result<Vec<ArchitecturalPattern>> {
        let mut patterns = Vec::new();
        
        for detector in &self.pattern_detectors {
            if let Some(pattern) = detector.detect(graph)? {
                patterns.push(pattern);
            }
        }
        
        Ok(patterns)
    }
    
    pub fn detect_drift(&self, 
                        graph: &DependencyGraph, 
                        patterns: &[ArchitecturalPattern]) -> Result<Vec<DriftViolation>> {
        let mut violations = Vec::new();
        
        for pattern in patterns {
            for boundary in &pattern.boundaries {
                let boundary_violations = self.check_boundary(graph, boundary)?;
                violations.extend(boundary_violations);
            }
        }
        
        Ok(violations)
    }
    
    pub fn infer_boundaries(&self, graph: &DependencyGraph) -> Result<Vec<ArchitectureBoundary>> {
        let mut boundaries = Vec::new();
        
        for inferencer in &self.boundary_inferencers {
            boundaries.extend(inferencer.infer(graph)?);
        }
        
        Ok(boundaries)
    }

    /// Extract minimal token-optimized subgraph context slice specifically formatted for Frontier LLM prompts
    pub fn slice_context_for_prompt(&self, graph: &DependencyGraph, file: &str, depth: usize) -> Result<String> {
        let node_id = NodeId(format!("{}::file", file));
        let callers = graph.get_callers(&node_id);
        let callees = graph.get_callees(&node_id);
        let deps = graph.get_dependencies(&node_id)?;

        let mut out = String::new();
        out.push_str(&format!("<architectural_context target_file=\"{}\">\n", file));
        out.push_str("  <incoming_dependents>\n");
        for caller in callers {
            out.push_str(&format!("    <dependent id=\"{}\"/>\n", caller.0));
        }
        out.push_str("  </incoming_dependents>\n");
        out.push_str("  <outgoing_dependencies>\n");
        for dep in deps {
            out.push_str(&format!("    <dependency id=\"{}\"/>\n", dep.0));
        }
        out.push_str("  </outgoing_dependencies>\n");
        out.push_str("</architectural_context>");

        Ok(out)
    }

    /// Synthesize automatic AI rule guidelines (.cursorrules / CLAUDE.md / AGENTS.md format)
    pub fn generate_ai_guidelines(&self, graph: &DependencyGraph) -> Result<String> {
        let boundaries = self.infer_boundaries(graph)?;
        let mut doc = String::new();
        doc.push_str("# 🤖 Auto-Generated CKB Architectural Guidelines\n\n");
        doc.push_str("> This document is automatically generated by CKB. Do NOT break these architectural rules when modifying code.\n\n");
        doc.push_str("## Inferred Architectural Boundaries\n\n");

        for b in boundaries {
            doc.push_str(&format!("### Boundary: {}\n", b.name));
            doc.push_str(&format!("- **Kind**: {:?}\n", b.kind));
            if !b.allowed_dependencies.is_empty() {
                doc.push_str(&format!("- **Allowed Imports**: {}\n", b.allowed_dependencies.join(", ")));
            }
            if !b.forbidden_dependencies.is_empty() {
                doc.push_str(&format!("- ⚠️ **FORBIDDEN Imports**: {}\n", b.forbidden_dependencies.join(", ")));
            }
            doc.push_str("\n");
        }

        doc.push_str("## Key Architectural Guardrails for AI\n");
        doc.push_str("1. Maintain separation of concerns between core logic, backend API, and presentation layers.\n");
        doc.push_str("2. Do not introduce circular dependencies across modules.\n");
        doc.push_str("3. Always query CKB MCP server for blast-radius impact analysis before deleting public interfaces.\n");

        Ok(doc)
    }

    /// Self-Healing Refactoring Engine: Uses graph partitioning to suggest exact decoupled interface extractions
    pub fn suggest_decoupling_refactor(&self, graph: &DependencyGraph, cycle_nodes: &[NodeId]) -> Result<String> {
        let mut refactor_plan = String::new();
        refactor_plan.push_str("🛠️ **CKB Self-Healing Refactoring Recommendation**\n\n");
        refactor_plan.push_str("Detected tightly coupled cycle. Proposed Interface Isolation Plan:\n");
        for (idx, node) in cycle_nodes.iter().enumerate() {
            refactor_plan.push_str(&format!("  {}. Extract shared contract interface for node `{}` into `interfaces/` module.\n", idx + 1, node.0));
        }
        refactor_plan.push_str("\nApplying this refactoring reduces cycle degree from 1.0 down to 0.0.");
        Ok(refactor_plan)
    }

    /// Predictive Failure Probability Index: Computes node centrality & fan-in risk score
    pub fn predict_failure_probability(&self, graph: &DependencyGraph, file: &str) -> Result<f32> {
        let node_id = NodeId(format!("{}::file", file));
        let inc = graph.incoming_degree(&node_id)?;
        let out = graph.outgoing_degree(&node_id)?;

        // High coupling + high fan-in = high failure probability index
        let coupling_score = (inc * 2 + out) as f32 / 15.0;
        let risk = coupling_score.min(0.99);

        Ok(risk)
    }
    
    fn check_boundary(&self, graph: &DependencyGraph, boundary: &ArchitectureBoundary) -> Result<Vec<DriftViolation>> {
        let mut violations = Vec::new();
        Ok(violations)
    }
}

pub trait PatternDetector: Send + Sync {
    fn detect(&self, graph: &DependencyGraph) -> Result<Option<ArchitecturalPattern>>;
}

pub trait BoundaryInferencer: Send + Sync {
    fn infer(&self, graph: &DependencyGraph) -> Result<Vec<ArchitectureBoundary>>;
}

